package ec.com.dinersclub.dddmodules.services;

import org.springframework.http.HttpHeaders;
import ec.com.dinersclub.dddmodules.domain.assessment.RecEvaluatePartyAuthenticationAssessmentRq;
import ec.com.dinersclub.dddmodules.domain.assessment.RecEvaluatePartyAuthenticationAssessmentRs;
import ec.com.dinersclub.dddmodules.domain.assessment.RecRetrievePartyAuthenticationAssessmentRq;
import ec.com.dinersclub.dddmodules.domain.assessment.RecRetrievePartyAuthenticationAssessmentRs;

public interface PartyAuthenticationAssessmentQueryUseCase {
	public RecEvaluatePartyAuthenticationAssessmentRs verifyDataClient(RecEvaluatePartyAuthenticationAssessmentRq request, HttpHeaders headers);
	public RecRetrievePartyAuthenticationAssessmentRs verifyProfile(RecRetrievePartyAuthenticationAssessmentRq request, HttpHeaders headers);	
}	
